version: '3'

services:
  zeplin_mta_mongo:
    image: mongo:6.0
    container_name: zeplin_mta_mongo
    restart: always
    ports:
      - "${ZEPLIN_MTA_MONGO_PORT:-27018}:27017"
  zeplin_mta_redis:
    image: redis:5
    container_name: zeplin_mta_redis
    restart: always
    ports:
      - "${ZEPLIN_MTA_REDIS_PORT:-6380}:6379"
