on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

name: Daily

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set git config
        run: |
          git config --global user.name zeplin-dev
          git config --global user.email zeplin-dev@users.noreply.github.com

      - name: Install dev-tools
        run: npm i -g git+ssh://git@github.com/zeplin/dev-tools.git#v3.x.x

      - name: Run audit fix
        run: npm run audit-fix
