on:
  workflow_run:
    workflows:
      - "Check Code Quality"
    branches:
      - main
    types:
      - completed
  release:
    types:
      - published

name: Build and Push to ECR

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.action == 'published' }}
    name: Build and Push
    uses: ./.github/workflows/reusable-docker-publish.yaml
    with:
      environment: ${{ startsWith(github.ref, 'refs/tags/') && 'prod' || 'dev' }}
    secrets: inherit
